services:
  gamehub_db:
    image: mysql:9.5.0
    container_name: gamehub_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - gamehub_db_data:/var/lib/mysql
      - ./data/database/init:/docker-entrypoint-initdb.d

volumes:
  gamehub_db_data:
