-- MySQL Script generated by MySQL Workbench
-- Wed 30 Sep 2026 11:46:16 AM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema lol_esports
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lol_esports
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lol_esports` ;
USE `lol_esports` ;

-- -----------------------------------------------------
-- Table `lol_esports`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lol_esports`.`players` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `lol_esports`.`teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lol_esports`.`teams` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `short_name` VARCHAR(20) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `lol_esports`.`team_players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lol_esports`.`team_players` (
  `team_id` BIGINT UNSIGNED NOT NULL,
  `player_id` BIGINT UNSIGNED NOT NULL,
  `joined_at` DATETIME NOT NULL,
  `left_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`team_id`, `player_id`),
  INDEX `fk_team_players_player` (`player_id` ASC) VISIBLE,
  CONSTRAINT `fk_team_players_team`
    FOREIGN KEY (`team_id`)
    REFERENCES `lol_esports`.`teams` (`id`),
  CONSTRAINT `fk_team_players_player`
    FOREIGN KEY (`player_id`)
    REFERENCES `lol_esports`.`players` (`id`));


-- -----------------------------------------------------
-- Table `lol_esports`.`champions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lol_esports`.`champions` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `released_at` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `lol_esports`.`tournaments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lol_esports`.`tournaments` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `start_date` DATETIME NULL DEFAULT NULL,
  `end_date` DATETIME NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `lol_esports`.`tournament_teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lol_esports`.`tournament_teams` (
  `tournament_id` BIGINT UNSIGNED NOT NULL,
  `team_id` BIGINT UNSIGNED NOT NULL,
  `registered_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`tournament_id`, `team_id`),
  INDEX `fk_tournament_teams_team` (`team_id` ASC) VISIBLE,
  CONSTRAINT `fk_tournament_teams_tournament`
    FOREIGN KEY (`tournament_id`)
    REFERENCES `lol_esports`.`tournaments` (`id`),
  CONSTRAINT `fk_tournament_teams_team`
    FOREIGN KEY (`team_id`)
    REFERENCES `lol_esports`.`teams` (`id`));


-- -----------------------------------------------------
-- Table `lol_esports`.`matches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lol_esports`.`matches` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `tournament_id` BIGINT UNSIGNED NOT NULL,
  `team_a_id` BIGINT UNSIGNED NOT NULL,
  `team_b_id` BIGINT UNSIGNED NOT NULL,
  `format` ENUM('BO1', 'BO3', 'BO5') NOT NULL,
  `status` ENUM('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED') NOT NULL DEFAULT 'SCHEDULED',
  `winner_team_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `scheduled_at` DATETIME NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_matches_tournament` (`tournament_id` ASC) VISIBLE,
  INDEX `fk_matches_team_a` (`team_a_id` ASC) VISIBLE,
  INDEX `fk_matches_team_b` (`team_b_id` ASC) VISIBLE,
  INDEX `fk_matches_winner` (`winner_team_id` ASC) VISIBLE,
  CONSTRAINT `fk_matches_tournament`
    FOREIGN KEY (`tournament_id`)
    REFERENCES `lol_esports`.`tournaments` (`id`),
  CONSTRAINT `fk_matches_team_a`
    FOREIGN KEY (`team_a_id`)
    REFERENCES `lol_esports`.`teams` (`id`),
  CONSTRAINT `fk_matches_team_b`
    FOREIGN KEY (`team_b_id`)
    REFERENCES `lol_esports`.`teams` (`id`),
  CONSTRAINT `fk_matches_winner`
    FOREIGN KEY (`winner_team_id`)
    REFERENCES `lol_esports`.`teams` (`id`));


-- -----------------------------------------------------
-- Table `lol_esports`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lol_esports`.`games` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `match_id` BIGINT UNSIGNED NOT NULL,
  `game_number` INT UNSIGNED NOT NULL,
  `winner_team_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `started_at` DATETIME NULL DEFAULT NULL,
  `ended_at` DATETIME NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_game_number_per_match` (`match_id` ASC, `game_number` ASC) VISIBLE,
  INDEX `fk_games_match` (`match_id` ASC) VISIBLE,
  INDEX `fk_games_winner` (`winner_team_id` ASC) VISIBLE,
  CONSTRAINT `fk_games_match`
    FOREIGN KEY (`match_id`)
    REFERENCES `lol_esports`.`matches` (`id`),
  CONSTRAINT `fk_games_winner`
    FOREIGN KEY (`winner_team_id`)
    REFERENCES `lol_esports`.`teams` (`id`));


-- -----------------------------------------------------
-- Table `lol_esports`.`player_game_stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lol_esports`.`player_game_stats` (
  `game_id` BIGINT UNSIGNED NOT NULL,
  `player_id` BIGINT UNSIGNED NOT NULL,
  `team_id` BIGINT UNSIGNED NOT NULL,
  `champion_id` BIGINT UNSIGNED NOT NULL,
  `kills` INT UNSIGNED NOT NULL DEFAULT 0,
  `deaths` INT UNSIGNED NOT NULL DEFAULT 0,
  `assists` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`game_id`, `player_id`),
  INDEX `fk_player_game_stats_player` (`player_id` ASC) VISIBLE,
  INDEX `fk_player_game_stats_team` (`team_id` ASC) VISIBLE,
  INDEX `fk_player_game_stats_champion` (`champion_id` ASC) VISIBLE,
  CONSTRAINT `fk_player_game_stats_game`
    FOREIGN KEY (`game_id`)
    REFERENCES `lol_esports`.`games` (`id`),
  CONSTRAINT `fk_player_game_stats_player`
    FOREIGN KEY (`player_id`)
    REFERENCES `lol_esports`.`players` (`id`),
  CONSTRAINT `fk_player_game_stats_team`
    FOREIGN KEY (`team_id`)
    REFERENCES `lol_esports`.`teams` (`id`),
  CONSTRAINT `fk_player_game_stats_champion`
    FOREIGN KEY (`champion_id`)
    REFERENCES `lol_esports`.`champions` (`id`));


-- -----------------------------------------------------
-- Table `lol_esports`.`champion_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lol_esports`.`champion_roles` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lol_esports`.`champions_has_champion_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lol_esports`.`champions_has_champion_roles` (
  `champions_id` BIGINT UNSIGNED NOT NULL,
  `champion_roles_id` INT NOT NULL,
  PRIMARY KEY (`champions_id`, `champion_roles_id`),
  INDEX `fk_champions_has_champion_roles_champion_roles1_idx` (`champion_roles_id` ASC) VISIBLE,
  INDEX `fk_champions_has_champion_roles_champions1_idx` (`champions_id` ASC) VISIBLE,
  CONSTRAINT `fk_champions_has_champion_roles_champions1`
    FOREIGN KEY (`champions_id`)
    REFERENCES `lol_esports`.`champions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_champions_has_champion_roles_champion_roles1`
    FOREIGN KEY (`champion_roles_id`)
    REFERENCES `lol_esports`.`champion_roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
